#!/usr/bin/env bash

#------------------------------------------------------------------------------
# Project Name      -
# Started On        - Fri 11 Dec 15:38:54 GMT 2020
# Last Change       - Fri 11 Dec 20:51:40 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------

# Clean up, in-case we're reloading this file.
pkill sxhkd dunst compton

sxhkd &

xmodmap -e 'keysym F1 = Escape' -e 'keysym Caps_Lock = ' &

dunst -config "$HOME/.config/dunst/dunstrc" &
compton --config "$HOME/.config/compton.conf" -b &

read Gamma < "$HOME/.config/rs-gamma"
redshift -O ${Gamma}K &

case `hostname` in
	Z11)
		Interface='enp3s0'

		xset s off -dpms r rate 170 70 &

		# Just using this for Skype.
		[ -n "$SSH_AUTH_SOCK" ] || export `gnome-keyring-daemon`

		# Make sure bluetooth is available right out of the gate.
		#bluetoothctl <<-EOF
		#	power on
		#	discoverable off
		#	scan on
		#	exit
		#EOF

		if command -V rudbgvid 1> /dev/null 2>&1; then
			rudbgvid -r -i 9 &
		else
			feh --bg-center "$HOME/Pictures/background.jpg" &
		fi

		mocp -S & ;;
	Sam)
		Interface='wlp1s0'
		xset s off r rate 180 60 &
		feh --bg-center "$HOME/Pictures/background.jpg" & ;;
esac

#-----------------------------------------------------------BSPWM Configuration

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width 2
bspc config window_gap 24
#bspc config top_padding 24
#bspc config bottom_padding 24
#bspc config left_padding 24
#bspc config right_padding 24
bspc config click_to_focus any
bspc config focus_follows_pointer false
bspc config normal_border_color '#222222'
bspc config active_border_color '#431111'
bspc config focused_border_color '#431111'
bspc config presel_feedback_color '#000000'
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# Blow away rules in-case we're restarting.
bspc rule -r *

bspc rule -a 'Blueman-manager' state=pseudo_tiled
bspc rule -a 'mplayer2' state=pseudo_tiled
bspc rule -a 'Screenkey' manage=off
